@startuml

' Make a dashed line, alternative syntax for ..>
(*) -[dashed]-> "Give ID"

' Make line bold and use color name
"Give ID" -[#6666ff,dashed]-> "Opens Chrome"

' Only change the color with hexadecimal RGB code
"Opens Chrome" -[#6666ff,dashed]-> "Inserts ID into Text Box"

' Order of line style and color can be reversed
"Inserts ID into Text Box" -[#6666ff,dashed]-> "Clicks on Submit Query Button"

' Order of line style and color can be reversed
"Clicks on Submit Query Button" -[#6666ff,dashed]-> "Details about ID will be shown"

' Make line bold and use color name
"Details about ID will be shown" -[#6666ff,dashed]-> "Clicks on CSV Button"

' Order of line style and color can be reversed
"Clicks on CSV Button" -[#6666ff,dashed]-> "Temp files are downloaded"

' Order of line style and color can be reversed
"Temp files are downloaded" -[#6666ff,dashed]-> "Changes file extension of temp files to CSV"

' Order of line style and color can be reversed
"Changes file extension of temp files to CSV" -[#6666ff,dashed]-> "Reads file as Pandas Dataframe"

' Order of line style and color can be reversed
"Reads file as Pandas Dataframe" -[#6666ff,dashed]-> "Prints Dataframe"

' Use dotted line style
"Prints Dataframe" -[dotted]-> (*)

@enduml